# Generated by Django 5.1.2 on 2024-10-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_dutyroster_shift_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(blank=True, choices=[('SSLC', 'SSLC'), ('PG', 'PG'), ('12th', '12th'), ('UG', 'UG')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
